[project]
name = "teams-logger"
version = "0.5.1"
description = "Microsoft Teams logging handler for Python"
readme = "README.rst"
requires-python = ">=3.8"
authors = [ { name = "Anes Foufa", email = "anes.foufa@upply.com" } ]
dependencies = [
    "requests>=2.32.0"
]

[project.optional-dependencies]
dev = [
    "pydump>=1.2.0"
]

[project.urls]
Homepage = "https://github.com/AnesFoufa/python-teams-logger"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
